### PR TITLE
Support arm64 build with make arm64

### PR DESCRIPTION
**Pull request by xerial**
Added experimental support for building jvmkill for arm64 (jvmkill-arm64.so). This doesn't require using Arm machines as it uses a GCC cross compiler in a docker image of https://github.com/dockcross/dockcross

### CODE REVIEW

**Comment by electrum** [comment]
Thanks for contributing this. dockcross is interesting and a neat idea, but it seems overly complex. This project is a very simple C library that we can easily build on the target platform. With Docker for Mac (not sure about other platforms), it's easy to run an image for a different architecture, then use that to build directly:
```
docker run -v ~/src/jvmkill:/work -it arm64v8/centos:7 bash
yum -y install java-11-openjdk-devel gcc make
cd /work
JAVA_HOME=/usr/lib/jvm/java make
```
What do you think of something like the above? (ideally, we'd use an image that already has the JDK and compiler installed, but I don't know of such an image)

**Comment by xerial** [comment]
> it seems overly complex.

Yeah. I know :) Actually, we don't need to merge this PR. 

Using QEMU and some jdk image for arm64 might be a better approach. I will ask some internal Arm people for their best practices. 

Thanks for the comment.

**Comment by yuokada** [comment]
Just in my opinion. One of other solutions is to use `DOCKER_BUILDKIT`  and `output` option.

[Containerize Your Go Developer Environment \- Part 1 \- Docker Blog](https://www.docker.com/blog/containerize-your-go-developer-environment-part-1/)


```dockerfile
FROM multiarch/ubuntu-core:arm64-xenial AS build

ENV JAVA_HOME=/opt/java
RUN apt-get update -y && apt-get install -y curl make gcc
RUN mkdir ${JAVA_HOME} && \
    curl -L -C - https://corretto.aws/downloads/latest/amazon-corretto-11-aarch64-linux-jdk.tar.gz | tar zvxf - -C "${JAVA_HOME}" --strip-components 1
RUN mkdir /tmp/jvmkill ;\
    curl -L -C - https://github.com/airlift/jvmkill/archive/f30c886c3ffab8fcbc547402935ff3fd9424d129.tar.gz | tar zxvf - -C /tmp/jvmkill --strip-components 1 ;\
    cd /tmp/jvmkill ;\
    make

FROM scratch AS bin
COPY --from=build /tmp/jvmkill/libjvmkill.so /
```

```shell
$ DOCKER_BUILDKIT=1 docker build -f Dockerfile.ubuntu-arm64 --target bin --output bin/ .
```

**Comment by electrum** [comment]
We now publish a multi-architecture Docker image: `ghcr.io/airlift/jvmkill:latest`

With `docker buildx`, we can build for multiple architectures without cross compiling or using a specific base image.

**Pull request closed without merging**
